# ==========================
# == Jekyll Configuration ==
# ==========================
permalink: pretty
safe: false

# ==========================
# == Custom Configuration ==
# ==========================

title: Dadgum Box Scores
subtitle: "Every UNC basketball box score since 03-04."
url: http://dadgumboxscores.com/
description: "Every UNC basketball box score since 03-04."


