baseURL = "https://dadgumboxscores.com/"
languageCode = "en-us"
title = "Dadgum Box Scores"

[params]
    author = "Chris Gallo"
    description = "Every UNC basketball box score since 03-04."
    title = "Dadgum Box Scores"

